name: BranchValidation & CodeBuild

on:
  push:
    branches:
      - dev
      - stg
      - prd
  pull_request:
    branches:
      - dev
      - stg
      - prd
      - main

permissions:
  contents: read
  actions: write
  pull-requests: write

jobs:
  validate-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Source Branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"

          echo "SOURCE BRANCH: $SOURCE_BRANCH"
          echo "TARGET BRANCH: $TARGET_BRANCH"

          if [[ "$TARGET_BRANCH" == "dev" ]]; then
            if [[ ! "$SOURCE_BRANCH" =~ ^(feature|bug|fix)/.+$ ]]; then
              echo "❌ Branch name must start with 'feature/', 'bug/', or 'fix/' when PR target is 'dev'"
              exit 1
            fi
          fi

          if [[ "$TARGET_BRANCH" == "stg" ]]; then
            if [[ ! "$SOURCE_BRANCH" =~ ^promotion/.+$ ]]; then
              echo "❌ Only 'promotion/' branches can raise PRs to 'stg'"
              exit 1
            fi
          fi

          if [[ "$TARGET_BRANCH" == "prd" ]]; then
            if [[ ! "$SOURCE_BRANCH" =~ ^release/.+$ ]]; then
              echo "❌ Only 'release/' branches can raise PRs to 'prd'"
              exit 1
            fi
          fi

          if [[ "$TARGET_BRANCH" == "main" ]]; then
            if [[ "$SOURCE_BRANCH" != "prd" ]]; then
              echo "❌ Only 'prd' branch can raise PRs to 'main'"
              exit 1
            fi
          fi

          echo "✅ PR source branch is valid."

  code-validate:
    runs-on: ubuntu-latest
    needs: validate-pr
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.11.0
        with:
          maven-version: '3.9.6'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java CDK project
        run: mvn clean package
